### ISSUE TITLE
Community.mongodb.mongodb_user - Can't create a user

### ISSUE THREAD

**Issue by 770715** [ansible-collections/community.mongodb#220] opened 2020-10-16 15:42 UTC
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Community.mongodb.mongodb_user

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
```

##### CONFIGURATION

```paste below
Unavaliable
```

##### OS / ENVIRONMENT

Alpine Linux running in a container. Libs installed during start:

(1/50) Installing libbz2 (1.0.8-r1)
(2/50) Installing expat (2.2.9-r1)
(3/50) Installing libffi (3.3-r2)
(4/50) Installing gdbm (1.13-r1)
(5/50) Installing xz-libs (5.2.5-r0)
(6/50) Installing ncurses-terminfo-base (6.2_p20200523-r0)
(7/50) Installing ncurses-libs (6.2_p20200523-r0)
(8/50) Installing readline (8.0.4-r0)
(9/50) Installing sqlite-libs (3.32.1-r0)
(10/50) Installing python3 (3.8.5-r0)
(11/50) Installing yaml (0.2.4-r1)
(12/50) Installing py3-yaml (5.3.1-r0)
(13/50) Installing py3-asn1 (0.4.7-r2)
(14/50) Installing py3-cparser (2.20-r0)
(15/50) Installing py3-cffi (1.14.0-r2)
(16/50) Installing py3-idna (2.9-r0)
(17/50) Installing py3-asn1crypto (1.3.0-r0)
(18/50) Installing py3-six (1.15.0-r0)
(19/50) Installing py3-cryptography (2.9.2-r0)
(20/50) Installing py3-bcrypt (3.1.7-r2)
(21/50) Installing py3-pynacl (1.4.0-r0)
(22/50) Installing py3-paramiko (2.7.1-r0)
(23/50) Installing py3-markupsafe (1.1.1-r3)
(24/50) Installing py3-jinja2 (2.11.2-r0)
(25/50) Installing py3-pycryptodome (3.9.7-r0)
(26/50) Installing ansible (2.9.14-r0)
(27/50) Installing py3-appdirs (1.4.4-r1)
(28/50) Installing py3-ordered-set (4.0.1-r0)
(29/50) Installing py3-parsing (2.4.7-r0)
(30/50) Installing py3-packaging (20.4-r0)
(31/50) Installing py3-setuptools (47.0.0-r0)
(32/50) Installing py3-chardet (3.0.4-r4)
(33/50) Installing py3-certifi (2020.4.5.1-r0)
(34/50) Installing py3-urllib3 (1.25.9-r0)
(35/50) Installing py3-requests (2.23.0-r0)
(36/50) Installing py3-msgpack (1.0.0-r0)
(37/50) Installing py3-lockfile (0.12.2-r3)
(38/50) Installing py3-cachecontrol (0.12.6-r0)
(39/50) Installing py3-colorama (0.4.3-r0)
(40/50) Installing py3-distlib (0.3.0-r0)
(41/50) Installing py3-distro (1.5.0-r1)
(42/50) Installing py3-webencodings (0.5.1-r3)
(43/50) Installing py3-html5lib (1.0.1-r4)
(44/50) Installing py3-pytoml (0.1.21-r0)
(45/50) Installing py3-pep517 (0.8.2-r0)
(46/50) Installing py3-progress (1.5-r0)
(47/50) Installing py3-toml (0.10.1-r0)
(48/50) Installing py3-retrying (1.3.3-r0)
(49/50) Installing py3-contextlib2 (0.6.0-r0)
(50/50) Installing py3-pip (20.1.1-r0)
Executing busybox-1.31.1-r16.trigger
OK: 237 MiB in 64 packages
Collecting pymongo
  Downloading pymongo-3.11.0.tar.gz (771 kB)
Using legacy setup.py install for pymongo, since package 'wheel' is not installed.
Installing collected packages: pymongo
    Running setup.py install for pymongo: started
    Running setup.py install for pymongo: finished with status 'done'
Successfully installed pymongo-3.11.0

##### STEPS TO REPRODUCE

```yaml
- name: Create a database user
  community.mongodb.mongodb_user:
    login_user: "{{ mongo_admin_user_name }}"
    login_password: "{{ mongo_admin_user_password }}"
    database: admin
    name: "{{ mongodb_user }}"
    password: "{{ user_password }}"
    state: present
```

##### EXPECTED RESULTS

I expected to see a user created. All the variables exists, passwords tested manually. 

##### ACTUAL RESULTS

```paste below
TASK [configure_mongodb : Create a  database user] **********************
[WARNING]: Module did not set no_log for update_password
changed: [mongo-c]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NotMasterError: not master
fatal: [mongo-b]: FAILED! => {"changed": false, "msg": "Unable to add or update user: not master"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NotMasterError: not master
fatal: [mongo-d]: FAILED! => {"changed": false, "msg": "Unable to add or update user: not master"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NotMasterError: not master
fatal: [mongo-e]: FAILED! => {"changed": false, "msg": "Unable to add or update user: not master"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NotMasterError: not master
fatal: [mongo-a]: FAILED! => {"changed": false, "msg": "Unable to add or update user: not master"}
```

**Comment by rhysmeister** [comment] 2020-10-16 18:20
Not a bug. The module is returning an error of type NotMasterError. This means your MongoDB instance is not ready to accept any writes. Typically this can happen if you connect directly to a secondary (without providing rs details). In this case it might be because you are executing the module before the instance has settled. A short pause might help but you could also have config issue to look at.

**Comment by 770715** [comment] 2020-10-19 12:53
Thanks for the information. I do admit I have "secondary" hosts in my inventory but I did assume, the module will do some sort of check before trying to create a user. I also have masters in the same inventory but the user is not being created there.

**Comment by rhysmeister** [comment] 2020-10-19 15:09
This is the job of the driver rather than the module. You need to connect to the replicaset rather than the host. There are a couple of ways of doing this. The examples contain one such method...

```
- name: Add a user to database in a replica set, the primary server is automatically discovered and written to
  community.mongodb.mongodb_user:
    database: burgers
    name: bob
    replica_set: belcher
    password: 12345
    roles: readWriteAnyDatabase
    state: present
```

**Comment by rhysmeister** [comment] 2020-10-24 16:33
Assume this has clear up the confusion. Closing issue.

**Closed by rhysmeister** 2020-10-24 16:33 UTC
