### ISSUE TITLE
community.mongodb.mongodb_role fails due to showAuthenticationRestrictions expected bool, found int

### ISSUE THREAD

**Issue by joantomas** [ansible-collections/community.mongodb#564] opened 2023-04-04 10:45 UTC
##### SUMMARY
I'm trying to use mongodb_role and I always receive the same error from _check_command_response on helpers.py: 
```
"msg": "\"showAuthenticationRestrictions\" had the wrong type. Expected bool, found int, full error: {'operationTime': Timestamp(1680602964, 4), 'ok': 0.0, 'errmsg': '\"showAuthenticationRestrictions\" had the wrong type. Expected bool, found int', 'code': 14, 'codeName': 'TypeMismatch'... 
```

I think that it could be related to [this](https://github.com/ansible-collections/community.mongodb/blob/03fd8b5364399a7a2e0d43267b43c5b42217a585/plugins/modules/mongodb_role.py#L225) object that pymongo do not transform int to booleans:
```        rolesDoc = {
            'rolesInfo': 1,
            'showAuthenticationRestrictions': 1,
            'showPrivileges': 1
        }
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.mongodb.mongodb_role

##### ANSIBLE VERSION

```
ansible [core 2.14.3]
  config file = /workspace/ansible.cfg
  configured module search path = ['/home/tops/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/tops/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/tops/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.5.1  

# /usr/local/lib/python3.10/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.4.2  

```

**Comment by rhysmeister** [comment] 2023-04-04 10:56
Hello @joantomas,

Please provide the Playbook/Task definition for this. MongoDB version may also be useful. 

Cheers,

Rhys

**Comment by artemsafiyulin** [comment] 2023-04-04 11:07
Hi @rhysmeister! I have a same problem.

here is ansible task:
'- name: Create explainRole Role
  community.mongodb.mongodb_role:
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ mongodb_admin_pwd }}"
    login_database: "{{ mongodb_admin_db }}"
    replica_set: "{{ replica_set_name }}"
    name: explainRole
    database: admin
    privileges:
      - resource:
          db: ""
          collection: ""
        actions:
          - listIndexes
          - listCollections
          - dbStats
          - dbHash
          - collStats
          - find
      - resource:
          db: ""
          collection: "system.profile"
        actions:
          - indexStats
          - dbStats
          - collStats
    state: present'
    
    MongoDB version is 6.0
    pymongo version 4.1.1
    
    maybe its hel in investigation

**Comment by rhysmeister** [comment] 2023-04-04 18:53
I've put tests for your two specific cases in ...

https://github.com/ansible-collections/community.mongodb/pull/565

They seem to work without any code changes...

https://github.com/ansible-collections/community.mongodb/actions/runs/4611138419/jobs/8150538992?pr=565

I'm testing against Mongodb 5.0 & 6.0 with PyMongo 4.1.1. 

I can certainly implememnt the "fix" but I'm currently at a bit of a loss to explain why it's not working for you. The only difference I can see is the ansible-core version of 2.14.* 

@artemsafiyulin - Are you using 2.14.* as well?

I test up to 2.13.* so it could explain it.

Rhys

**Comment by rhysmeister** [comment] 2023-04-05 08:25
Works also with 2.14...

https://github.com/ansible-collections/community.mongodb/actions/runs/4615931651/jobs/8160861484?pr=565

Mystery!

**Comment by joantomas** [comment] 2023-04-05 08:43
Just to add extra context. I just tried on check mode. The tests are running on check-mode (dry-run) or applying changes?

**Comment by rhysmeister** [comment] 2023-04-05 09:43
Issue is in the role_find function. This always executes so check_mode will not play a role here.

**Comment by artemsafiyulin** [comment] 2023-04-05 09:58
Hi! @rhysmeister I just now noticed that I was getting an error on version 4.4 as well @joantomas . Perhaps this is the problem, because you run tests as you write for version 5.0 and 6.0.
If you execute manually in mongodb the command that you run in the role_find() function on different versions, we get the following results:

for version 4.4.
```
rs0:PRIMARY> db.version();
4.4.19
rs0:PRIMARY> db.runCommand({rolesInfo: 1, showAuthenticationRestrictions: 1, showPrivileges: 1})
{
        "operationTime" : Timestamp(1680688319, 1),
        "ok" : 0,
        "errmsg" : "\"showAuthenticationRestrictions\" had the wrong type. Expected bool, found double",
        "code" : 14,
        "codeName" : "TypeMismatch",
        "$clusterTime" : {
                "clusterTime" : Timestamp(1680688319, 1),
                "signature" : {
                        "hash" : BinData(),
                        "keyId" : NumberLong()
                }
        }
}
rs0:PRIMARY> db.runCommand({rolesInfo: 1, showAuthenticationRestrictions: true, showPrivileges: 1})
{
        "roles" : [ ],
        "ok" : 1,
        "$clusterTime" : {
                "clusterTime" : Timestamp(1680688329, 1),
                "signature" : {
                        "hash" : BinData(),
                        "keyId" : NumberLong()
                }
        },
        "operationTime" : Timestamp(1680688329, 1)
}
rs0:PRIMARY>
```

for version 6.0.
```
rs0 [direct: primary] test> db.version();
6.0.5
rs0 [direct: primary] test> db.runCommand({rolesInfo: 1, showAuthenticationRestrictions: 1, showPrivileges: 1})
{
  roles: [],
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1680688449, i: 1 }),
    signature: {
      hash: Binary(),
      keyId: Long()
    }
  },
  operationTime: Timestamp({ t: 1680688449, i: 1 })
}
rs0 [direct: primary] test> db.runCommand({rolesInfo: 1, showAuthenticationRestrictions: true, showPrivileges: 1})
{
  roles: [],
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1680688519, i: 1 }),
    signature: {
      hash: Binary(),
      keyId: Long()
    }
  },
  operationTime: Timestamp({ t: 1680688519, i: 1 })
}
rs0 [direct: primary] test> 
```

As you can see in version 4.4 it only works with true. And in version 6.0 it works with both 1 and true. Why this happens is really unclear, perhaps some fixes have been included since version 5.0.

**Comment by rhysmeister** [comment] 2023-04-05 10:06
@artemsafiyulin  - So do you get this error with 6.0 or not? It would make more sense if you didn't.

I've udpated the query doc in the code to use True where appropriate. If this works as expected I'm inclined to keep it.

**Comment by rhysmeister** [comment] 2023-04-05 14:42
Fix merged in https://github.com/ansible-collections/community.mongodb/pull/565

Not reproducable on 5 or 6 but I believe the fix will work for 4.*.

**Comment by rhysmeister** [comment] 2023-04-07 15:58
Fix release to Galaxy https://galaxy.ansible.com/community/mongodb

**Closed by rhysmeister** 2023-04-07 15:58 UTC
