### ISSUE TITLE
Issue with atlas cluster connection

### ISSUE THREAD

**Issue by rrondeau** [ansible-collections/community.mongodb#563] opened 2023-03-29 12:56 UTC
##### SUMMARY
I am currently in the process of upgrading my ansible stack to a newer version.
I had zero issue with the old version of this module (1.3.2 with pymongo 3.13.x) and i am trying to use 1.5.1 with pymongo 4.x.
I am using mongodb 6.0.5 in atlas.

I am using mongodb_status and mongodb_index, both gets the same error :
```
Unable to connect to database: Cannot specify multiple hosts with directConnection=true
```

Everything worked before the upgrade :/

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.mongodb.mongodb_status / community.mongodb.mongodb_index

##### ANSIBLE VERSION
```
ansible [core 2.14.4]
  config file = None
  configured module search path = ['/home/rrondeau/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rrondeau/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/rrondeau/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rrondeau/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/rrondeau/.local/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.5.1  
```

##### OS / ENVIRONMENT
debian / ansible installed with pip

##### STEPS TO REPRODUCE
```yaml
- name: Ensure replicaset is stable before beginning
  community.mongodb.mongodb_status:
    login_host: "mongodb+srv://{{ atlas_host }}"
    login_user: "admin"
    login_password: "{{ atlas_admin_password }}"
```
or
```yaml
- name: Create indices
  community.mongodb.mongodb_index:
    login_host: "mongodb+srv://{{ atlas_host }}"
    login_user: admin
    login_password: "{{ atlas_admin_password }}"
    indexes:
      - database: "{{ index.database }}"
        collection: "{{ index.collection }}"
        keys: "{{ index.attributes | items2dict }}"
        options:
          name: "{{ index.name }}"
        state: "{{ index.state }}"
  loop: "{{ atlas_indices }}"
  loop_control:
    loop_var: "index"
    label: "{{ index.name }}"
```

##### ACTUAL RESULTS
status :
```
Unable to connect to database: Cannot specify multiple hosts with directConnection=true
```
index :
```
Unable to determine if auth is enabled: Traceback (most recent call last):
  File "/tmp/ansible_community.mongodb.mongodb_index_payload_3hozcr89/ansible_community.mongodb.mongodb_index_payload.zip/ansible_collections/community/mongodb/plugins/module_utils/mongodb_common.py", line 291, in is_auth_enabled
    myclient = MongoClient(**connection_params)
  File "/home/rrondeau/.local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 785, in __init__
    _check_options(seeds, opts)
  File "/home/rrondeau/.local/lib/python3.9/site-packages/pymongo/uri_parser.py", line 392, in _check_options
    raise ConfigurationError("Cannot specify multiple hosts with directConnection=true")
pymongo.errors.ConfigurationError: Cannot specify multiple hosts with directConnection=true

unable to connect to database: local variable myclient referenced before assignment
```

**Comment by rhysmeister** [comment] 2023-03-29 17:10
Hi @rrondeau,

What's the value of atlas_host?

I've checked the docs and this has jumped out at me...

https://pymongo.readthedocs.io/en/stable/api/pymongo/mongo_client.html

```
directConnection (optional): if True, forces this client to

    connect directly to the specified MongoDB host as a standalone. If false, the client connects to the entire replica set of which the given MongoDB host(s) is a part. If this is True and a mongodb+srv:// URI or a URI containing multiple seeds is provided, an exception will be raised.
```

directConnect=True is harded coded in a lot of places. I'd have to check the PR for the exact reason but there was a change in Pymongo 4.0 that required this. Can you try without the *mongodb+srv://* part of the connection url?

Cheers,

Rhys

**Comment by rrondeau** [comment] 2023-03-30 09:02
Hi @rhysmeister 

The atlas_host is the SRV record of my atlas/mongodb cluster.
Its something like this : cluster-name.some-hash.cloud-provider.mongodb.net
Atlas provide this SRV record to automate the discovery of the clusters nodes, i dont have to search for the node list or master, the client will do the job, in that case its pymongo.

Without the mongodb+srv prefix, it does not work because its not a CNAME or A record :
```
[Errno -5] No address associated with hostname
```

My understanding is that directConnect force the connection to one node, i dont know if i can do that with an atlas cluster.
If i use the primary dns record with something like this `mongodb://my-primary-node:27017` i get this error :
```
Unable to determine if auth is enabled: Traceback (most recent call last):
  File "/tmp/ansible_community.mongodb.mongodb_status_payload_98fi7uqb/ansible_community.mongodb.mongodb_status_payload.zip/ansible_collections/community/mongodb/plugins/module_utils/mongodb_common.py", line 292, in is_auth_enabled
    myclient[admin].command(listDatabases, 1.0)
  File "/home/rrondeau/.local/lib/python3.9/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rrondeau/.local/lib/python3.9/site-packages/pymongo/database.py", line 805, in command
    with self.__client._socket_for_reads(read_preference, session) as (
  File "/home/rrondeau/.local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1296, in _socket_for_reads
    server = self._select_server(read_preference, session)
  File "/home/rrondeau/.local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1257, in _select_server
    server = topology.select_server(server_selector)
  File "/home/rrondeau/.local/lib/python3.9/site-packages/pymongo/topology.py", line 272, in select_server
    server = self._select_server(selector, server_selection_timeout, address)
  File "/home/rrondeau/.local/lib/python3.9/site-packages/pymongo/topology.py", line 261, in _select_server
    servers = self.select_servers(selector, server_selection_timeout, address)
  File "/home/rrondeau/.local/lib/python3.9/site-packages/pymongo/topology.py", line 223, in select_servers
    server_descriptions = self._select_servers_loop(selector, server_timeout, address)
  File "/home/rrondeau/.local/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: my-primary-node:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 64254e8f819fd08ffd85c4bf, topology_type: Single, servers: [<ServerDescription (my-primary-node, 27017) server_type: Unknown, rtt: None, error=NetworkTimeout(my-primary-node:27017: timed out)>]>
```

I will try to make a workaround in the meantime.

Thanks for the quick reply

**Comment by rhysmeister** [comment] 2023-03-31 12:24
Hello @rrondeau,

I don't test against Atlas so it's not possible to catch these issues. I'm happy to consider a fix if you have any suggestions.

Cheers,

Rhys

**Comment by rhysmeister** [comment] 2023-04-18 09:44
No further feedback. Please feel free to reopen if you feel the need.

**Comment by apinter** [comment] 2023-04-18 11:51
Just ran into this same problem :D 

If I specify the `auth_type` to SCRAM-SHA-1 I get 
```
fatal: [st9-mongo]: FAILED! => {"changed": false, "msg": "Unable to connect to database: SCRAM-SHA-1 requires a username."}
```

If I don't then I get a DNS error or just runs into a connection timeout :)
What can I do to help?


What can I help with?

**Comment by rhysmeister** [comment] 2023-04-18 12:28
Hello @apinter,

Are you gettting the error message above as well? You are also using Atlas?

"Unable to connect to database: Cannot specify multiple hosts with directConnection=true"

"Unable to connect to database: SCRAM-SHA-1 requires a username." - Did you provide a username? Please paste the relevant tasks and error messaghe for all you mentioned problems. 

Rhys

**Comment by apinter** [comment] 2023-04-19 05:23
As promised some details from my end on the issue:
The node I'm trying to run this from has `pymongo 4.3.3` installed, using the latest community.mongodb collection. 

The task:

```yaml
- hosts: st9
  become: false
  gather_facts: true
  vars_files:
    - vars/js_path.env
  tasks:
    - name: Find replicaset members
      community.mongodb.mongodb_status:
        login_host: "adathors-shard-00-01.y1ag0.mongodb.net"
        login_user: "apinter_st9"
        login_password: "{{ atlas_pw }}"
        auth_mechanism: "SCRAM-SHA-1"
        ssl: true
        poll: 1
        interval: 5
        strict_compatibility: false
      register: rs
```

This will end with the following error: 
` fatal: [st9-mongo]: FAILED! => {"changed": false, "msg": "Unable to connect to database: SCRAM-SHA-1 requires a username."}`

### If I change the task and exclude the `auth_mechanism`:

```yaml
- hosts: st9
  become: false
  gather_facts: true
  vars_files:
    - vars/js_path.env
  tasks:
    - name: Find replicaset members
      community.mongodb.mongodb_status:
        login_host: "adathors-shard-00-01.y1ag0.mongodb.net"
        login_user: "apinter_st9"
        login_password: "{{ atlas_pw }}"
        # auth_mechanism: "SCRAM-SHA-1"
        ssl: true
        poll: 1
        interval: 5
        strict_compatibility: false
      register: rs
```

I get the following (sorry about the messy output, don't want to alter it in any way):

```
fatal: [st9-mongo]: FAILED! => {"changed": false, "msg": "Unable to determine if auth is enabled: Traceback (most recent call last):\n  File \"/tmp/ansible_community.mongodb.mongodb_status_payload_t4bzrewd/ansible_community.mongodb.mongodb_status_payload.zip/ansible_collections/community/mongodb/plugins/module_utils/mongodb_common.py\", line 293, in is_auth_enabled\n    myclient['admin'].command('listDatabases', 1.0)\n  File \"/home/ansibleci/.local/lib/python3.10/site-packages/pymongo/_csot.py\", line 105, in csot_wrapper\n    return func(self, *args, **kwargs)\n  File \"/home/ansibleci/.local/lib/python3.10/site-packages/pymongo/database.py\", line 805, in command\n    with self.__client._socket_for_reads(read_preference, session) as (\n  File \"/home/ansibleci/.local/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 1296, in _socket_for_reads\n    server = self._select_server(read_preference, session)\n  File \"/home/ansibleci/.local/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 1257, in _select_server\n    server = topology.select_server(server_selector)\n  File \"/home/ansibleci/.local/lib/python3.10/site-packages/pymongo/topology.py\", line 272, in select_server\n    server = self._select_server(selector, server_selection_timeout, address)\n  File \"/home/ansibleci/.local/lib/python3.10/site-packages/pymongo/topology.py\", line 261, in _select_server\n    servers = self.select_servers(selector, server_selection_timeout, address)\n  File \"/home/ansibleci/.local/lib/python3.10/site-packages/pymongo/topology.py\", line 223, in select_servers\n    server_descriptions = self._select_servers_loop(selector, server_timeout, address)\n  File \"/home/ansibleci/.local/lib/python3.10/site-packages/pymongo/topology.py\", line 238, in _select_servers_loop\n    raise ServerSelectionTimeoutError(\npymongo.errors.ServerSelectionTimeoutError: adathors-shard-00-01.y1ag0.mongodb.net:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 643f77d9ba61534a7edbe13d, topology_type: Single, servers: [<ServerDescription ('adathors-shard-00-01.y1ag0.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('adathors-shard-00-01.y1ag0.mongodb.net:27017: [Errno -2] Name or service not known')>]>\n"}
```

### If I add `mongodb+srv://` to the `login_host`: 

```yaml
- hosts: st9
  become: false
  gather_facts: true
  vars_files:
    - vars/js_path.env
  tasks:
    - name: Find replicaset members
      community.mongodb.mongodb_status:
        login_host: "adathors-shard-00-01.y1ag0.mongodb.net"
        login_user: "apinter_st9"
        login_password: "{{ atlas_pw }}"
        # auth_mechanism: "SCRAM-SHA-1"
        ssl: true
        poll: 1
        interval: 5
        strict_compatibility: false
      register: rs
```

I get the following error:

`fatal: [st9-mongo]: FAILED! => {"changed": false, "msg": "Unable to connect to database: The DNS query name does not exist: _mongodb._tcp.adathors-shard-00-01.y1ag0.mongodb.net."}`

I did see the `Unable to connect to database: Cannot specify multiple hosts with directConnection=true`, but since I'm a muppet I can't remember the task settings to reproduce that :/

Let me know if I can help further the issue!

**Comment by rhysmeister** [comment] 2023-04-19 06:02
You're running agains the hostgroup **st9**. Can you check the DNS resolution for adathors-shard-00-01.y1ag0.mongodb.net on that specific host?

When you use mongodb+srv:// in the url the hostname seems to be transformed to...

`_mongodb._tcp.adathors-shard-00-01.y1ag0.mongodb.net`

I guess this must be specfic to Atlas. Do you know anything about this?

**Comment by apinter** [comment] 2023-04-19 06:57
> You're running agains the hostgroup st9. Can you check the DNS resolution for adathors-shard-00-01.y1ag0.mongodb.net on that specific host?

Yes, that is essentially a bastion node to be able to access the rs in Atlas. Funny thing is that now I tried with `mongosh` and got a 30s timeout as well. Very strange. Going to dig into this and report back.

**Comment by apinter** [comment] 2023-04-19 07:34
So, it seems that the connection string that the Atlas UI spits out when one wants to connect via mongosh or pymongo or a different driver is simply stupid. 
I used the connection string - uri only - what we pass to our application and was able to reproduce the `  msg: 'Unable to connect to database: Cannot specify multiple hosts with directConnection=true'` error. This is the string:

```yaml
        login_host: "mongodb://adathors-shard-00-00-pri.y1ag0.mongodb.net:27017,adathors-shard-00-01-pri.y1ag0.mongodb.net:27017,adathors-shard-00-02-pri.y1ag0.mongodb.net"
```

Made sense so I dropped the last 2 uri and got a connection: 

```yaml
        login_host: "mongodb://adathors-shard-00-00-pri.y1ag0.mongodb.net:27017"
```

But right at that point I ran into the next issue in which case the uri doesn't match the ones I've been using to connect to:
```yaml
TASK [ansible.builtin.debug] ***************************************************************************************************************************
ok: [st9-mongo] => 
  rs:
    changed: false
    failed: false
    iterations: 1
    msg: replicaset is in a converged state
    replicaset:
      atlas-<REDACTED>-shard-00-00.y1ag0.mongodb.net:27017: SECONDARY
      atlas-<REDACTED>-shard-00-01.y1ag0.mongodb.net:27017: PRIMARY
      atlas-<REDACTED>-shard-00-02.y1ag0.mongodb.net:27017: SECONDARY
```
In this case `adathors-shard-00-00-pri.y1ag0.mongodb.net` == `atlas-<REDACTED>-shard-00-00.y1ag0.mongodb.net:27017` which will not allow connections. Likely an internal address used by the nodes. 
The point of this task would be to find the primary node and store the address, and pass it over to the next task that would execute js scripts against the primary, but it simply can't connect to the instance with that address. I understand that this is more of an Atlas related problem, but would it be possible to make the `directConnection` optional? Would that even remotely solve the issue tho? :thinking:

**Comment by rhysmeister** [comment] 2023-04-19 08:06
Hi @apinter,

Any DNS issues I would expect to come from the underlying host, not anything in the collection code. I'm not doing anything funky in that area.

Once you solve this I would expect you will see the directConnection error again. I run tests against vanilla MongoDB installed on Debian/Redhat flavour LInux but not against Atlas specifically. I know people have used at least some of the modules sucessfully with Atlas in the past. There is a specific page in the pymongo docs about Atlas

https://pymongo.readthedocs.io/en/stable/atlas.html

What is the format of this url given?

f you want to execute scripts against the PRIMARY why can't you just connect to the replicaset, which will direct writes to the PRIMARY. Or do you have some specific use I'm not thinking of?

re directConnection: I could make this a parameter. If you're willing to do some monkey patching we might be able to do something here. The directConnect code is also used to determine if auth is enable. Is it even possible to run Atlas without auth? I would guess not but I've never checked this. An option might be to skip all the default connect code and introduce one specifically for Atlas.

Cheers,

Rhys

**Comment by rrondeau** [comment] 2023-04-20 08:30
Yeah i pretty sure my changes break things but i only use atlas on my side.
I dont know the module structure, i removed the is_auth_enabled check because thats where the directConnection is enforced.
Is-it still possible to install mongodb without auth ?

To be honest, i dont know if you need to make a new auth path.
Maybe the module need to just build the uri (with or without the auth) and just give it to pymongo and let the driver do his thing.

**Comment by apinter** [comment] 2023-04-20 11:26
> Here is my monkey patch :
> 
> ```
> @@ -328,20 +328,15 @@
>  
>      if 'create_for_localhost_exception' not in module.params and fail_msg is None:
>          try:
> -            if is_auth_enabled(module):
> -                if login_user is not None and login_password is not None:
> -                    if int(PyMongoVersion[0]) < 4:  # pymongo < 4
> -                        client.admin.authenticate(login_user, login_password, source=login_database)
> -                    else:  # pymongo >= 4. There's no authenticate method in pymongo 4.0. Recreate the connection object
> -                        client = get_mongodb_client(module, login_user, login_password, login_database, directConnection=directConnection)
> -                else:
> -                    fail_msg = 'No credentials to authenticate'
> +            if login_user is not None and login_password is not None:
> +                if int(PyMongoVersion[0]) < 4:  # pymongo < 4
> +                    client.admin.authenticate(login_user, login_password, source=login_database)
> +                else:  # pymongo >= 4. There's no authenticate method in pymongo 4.0. Recreate the connection object
> +                    client = get_mongodb_client(module, login_user, login_password, login_database)
> +            else:
> +                fail_msg = 'No credentials to authenticate'
>          except Exception as excep:
>              fail_msg = 'unable to connect to database: %s' % to_native(excep)
> -        # Get server version:
> -        if fail_msg is None:
> -            srv_version = check_srv_version(module, client)
> -            check_driver_compatibility(module, client, srv_version)
>      elif fail_msg is None:  # this is the mongodb_user module
>          if login_user is not None and login_password is not None:
>              if int(PyMongoVersion[0]) < 4:  # pymongo < 4
> ```

This indeed worked for me too connecting with `mongodb+srv` to the cluster. I also had to change [directConenction](https://github.com/ansible-collections/community.mongodb/blob/master/plugins/module_utils/mongodb_common.py#L254) to `false`. Thank you for sharing it!

**Comment by rhysmeister** [comment] 2023-04-23 13:52
Hello All,

Possible fix...

[community-mongodb-latest.tar.gz](https://github.com/ansible-collections/community.mongodb/files/11303885/community-mongodb-latest.tar.gz)

I've verified this doesn't affect standard MongoDB but I can't verifixy against Atlas. That's where you come in. Please have a go at testing this when you can. I have introduced a new parameter "atlas_auth" that will skip the stnadard authentication path. Please test at least the mongodb_user and one other module (they use slightly diffferent paths).

Cheers,

Rhys

**Comment by apinter** [comment] 2023-04-26 14:49
> I've verified this doesn't affect standard MongoDB but I can't verifiy against Atlas. That's where you come in. 

Apologies for the delay, going to test this tomorrow.

**Comment by rrondeau** [comment] 2023-04-26 14:52
I will also be able to test this when things settle down at work, maybe next week.

**Comment by rhysmeister** [comment] 2023-04-27 17:33
No rush. Thanks for your efforts so far.

**Comment by rrondeau** [comment] 2023-05-17 09:42
It works :)

**Comment by rhysmeister** [comment] 2023-05-17 12:16
Hi @rrondeau,

It would be good to also test the mongodb_user module since this uses a different auth path.

Rhys

**Comment by rrondeau** [comment] 2023-05-17 14:56
Hi @rhysmeister 

Got the classic error of directConnection but i create my db users through the Atlas API.
The doc says this is not supported anyway : https://www.mongodb.com/docs/atlas/security-add-mongodb-users/#add-database-users

**Comment by rhysmeister** [comment] 2023-05-17 16:15
Hi @rrondeau,

Not sure I follow. What exactly is not supported?

Rhys

**Comment by rrondeau** [comment] 2023-05-17 16:31
You cannot create users in the databases, the users are project wide (multi cluster) on the atlas side.
So the mongodb_user module as no real world usage in the atlas scenario.

**Comment by rhysmeister** [comment] 2023-05-17 17:02
OK. alles klar! Thanks for your input.

Rhys

**Comment by apinter** [comment] 2023-06-12 06:05
My apologies for the silence, been a bit hectic the past few weeks. Anyhow, I would be still interested in helping out and have the problem solved. I hopefully will be able to get a small Atlas cluster provided to the project in the near future for testing purposes. 
Hoping to jump back in the action this week ;)

**Comment by rhysmeister** [comment] 2023-07-10 17:22
A least one other user has reported using several modules successfully with Atlas. Assuming all good so closing.

**Closed by rhysmeister** 2023-07-10 17:22 UTC

**Comment by rrondeau** [comment] 2023-07-10 17:35
Thanks again @rhysmeister
Will try to update to 1.6.x after my vacations.
